### ISSUE TITLE
数据集可以分享下么？

### ISSUE THREAD

**Issue by Andrawzyf** [luckynote/300VW_landmarks#2]
我点了你给的那个连接，下的咋全是行人的数据集合。。。。有具体连接么。。。万分感谢。。

**Comment by luckynote** [comment]
https://ibug.doc.ic.ac.uk/download/300VW_Dataset_2015_12_14.zip/
You need request.

**Comment by Andrawzyf** [comment]
@luckynote 谢谢，我试试
